services:
  - type: web
    name: life-reminder-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: PORT
        value: 10000
      - key: EMAIL
        sync: false
      - key: PASS
        sync: false
      - key: RESEND
        sync: false